### ISSUE TITLE
Client attribute cannot be found in python after importing pilosa

### ISSUE THREAD

**Issue by vivekkumar159** [pilosa/python-pilosa#44]
I have installed pilosa library for python(2.7.13), but whenever i'm using client function, then i'm getting the following error.
Traceback (most recent call last):
  File "pilosa.py", line 1, in <module>
    import pilosa
  File "/Users/vivek.ku/pilosa/pilosa.py", line 5, in <module>
    client = pilosa.Client()
AttributeError: 'module' object has no attribute 'Client'

**Comment by travisturner** [comment]
hey @vivekkumar159 
when you have `import pilosa` in a file called `pilosa.py`, then python is importing `python.py` instead of the pilosa client library. if you change the name of your `pilosa.py` file to something else it should work. (also be sure to remove the `pilosa.pyc` file if you have one).

**Comment by vivekkumar159** [comment]
Thanks, it worked.

**Comment by travisturner** [comment]
great, thanks for trying it out!
let us know if you have any other questions or feedback.
